version: "3.7"

services:
  laravel:
    build: .
    ports:
      - "80:80"
      - "9000:9000"
    volumes:
      - /var/www/html:/var/www/html
    networks:
      - backend
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - backend
networks:
  backend: